export const YOUTUBE_LIST = "YOUTUBE_LIST"
export const YOUTUBE_DETAILS = "YOUTUBE_DETAILS"
export const CLEAR_YOUTUBE_DETAILS = "CLEAR_YOUTUBE_DETAILS"

export const MOVIES_LIST = "MOVIES_LIST"
export const MOVIES_LIST_SEARCH = "MOVIES_LIST_SEARCH"
export const MOVIES_DETAILS = "MOVIES_DETAILS"
export const CLEAR_MOVIES_DETAILS = "CLEAR_MOVIES_DETAILS"

export const GITHUB_GET_USER = "GITHUB_GET_USER"
export const GITHUB_GET_FOLLOWERS = "GITHUB_GET_FOLLOWERS"
export const GITHUB_GET_FOLLOWINGS = "GITHUB_GET_FOLLOWINGS"
export const GITHUB_GET_REPOS = "GITHUB_GET_REPOS"

export const LIST_COCKTAILS = "LIST_COCKTAILS"
export const LIST_SEARCH_COCKTAILS = "LIST_SEARCH_COCKTAILS"
export const FILTER_COCKTAILS = "FILTER_COCKTAILS"
export const LIST_COCKTAIL_DETAILS = "LIST_COCKTAIL_DETAILS"
export const CLEAR_COCKTAIL_DETAILS = "CLEAR_COCKTAIL_DETAILS"
export const COCKTAIL_INGREDIENTS = "COCKTAIL_INGREDIENTS"

export const LIST_GIF = "LIST_GIF"

export const NEWS_LIST = "NEWS_LIST"

export const POKEMON_LIST = "POKEMON_LIST"

export const RANDOM_USER_LIST = "RANDOM_USER_LIST"

export const TO_DO_LIST = "TO_DO_LIST"
export const CREATE_TO_DO = "CREATE_TO_DO"
export const DELETE_TODO = "DELETE_TODO"
export const DONE_TODO = "DONE_TODO"
export const EDIT_TODO = "EDIT_TODO"

export const GET_WEATHER = "GET_WEATHER"